default: &default
    adapter: postgresql
    encoding: unicode
    host: db
    username: postgres
    password: postgres
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sanpomiti_app_development

test:
  <<: *default
  database: sanpomiti_app_test
  host: <%= ENV['PGHOST'] || 'db' %>

production:
  <<: *default
  database: sanpomiti_app_production
  username: sanpomiti_app
  password: <%= ENV['SANPOMITI_APP_DATABASE_PASSWORD'] %>
